require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/menus", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Menu. As you add validations to Menu, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    attributes_for(:menu).merge({ restaurant_id: restaurant.id })
  }

  let(:restaurant) {
    create(:restaurant)
  }

  let(:invalid_attributes) {
    valid_attributes.merge({ name: nil })
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # MenusController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Menu.create! valid_attributes
      get menus_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      menu = Menu.create! valid_attributes
      get menu_url(menu), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Menu" do
        expect {
          post menus_url,
               params: { menu: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Menu, :count).by(1)
      end

      it "renders a JSON response with the new menu" do
        post menus_url,
             params: { menu: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Menu without a name" do
        expect {
          post menus_url,
               params: { menu: invalid_attributes }, as: :json
        }.to change(Menu, :count).by(0)
      end

      it "does not create a new Menu without availability" do
        expect {
          post menus_url,
               params: { menu: valid_attributes.merge({ availability: nil }) }, as: :json
        }.to change(Menu, :count).by(0)
      end

      it "does not create a new Menu without day period" do
        expect {
          post menus_url,
               params: { menu: valid_attributes.merge({ day_period: nil }) }, as: :json
        }.to change(Menu, :count).by(0)
      end

      it "renders a JSON response with errors for the new menu" do
        post menus_url,
             params: { menu: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          availability: "seasonal",
          day_period: "lunch",
          name: "Cozy Family Menu",
          description: "Menu for a cozy family lunch"
        }
      }

      it "updates the requested menu" do
        menu = Menu.create! valid_attributes
        patch menu_url(menu),
              params: { menu: new_attributes }, headers: valid_headers, as: :json
        menu.reload
        changed_attributes = menu.attributes.slice("availability", "day_period", "name", "description")

        expect(changed_attributes.values).to eq(new_attributes.values)
      end

      it "renders a JSON response with the menu" do
        menu = Menu.create! valid_attributes
        patch menu_url(menu),
              params: { menu: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the menu" do
        menu = Menu.create! valid_attributes
        patch menu_url(menu),
              params: { menu: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested menu" do
      menu = Menu.create! valid_attributes
      expect {
        delete menu_url(menu), headers: valid_headers, as: :json
      }.to change(Menu, :count).by(-1)
    end
  end
end
